language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: build
  on:
    branch: main
  